### ISSUE TITLE
Bad event polyfills

### ISSUE THREAD

**Issue by adgang** [FredKSchott/rollup-plugin-polyfill-node#22] opened 2021-05-11 20:07 UTC
Event polyfills look like this:
```
var events = /*#__PURE__*/Object.freeze({
  __proto__: null,
  'default': EventEmitter,
  EventEmitter: EventEmitter
});
```
I believe this should not be the behaviour.

Please see this discussion for details:
https://github.com/snowpackjs/snowpack/discussions/1480

**Comment by quolpr** [comment] 2021-05-20 12:09
So, I investigated that polyfill is incorrect. Here how node makes export - https://github.com/nodejs/node/blob/v16.2.0/lib/events.js#L77

And I am not sure how to fix it. Cause as I understand, polyfill uses ESM, but other packages use CJS style(trough `require`). And I am not sure how to make that ESM export(that is used in this lib, https://github.com/snowpackjs/rollup-plugin-polyfill-node/blob/main/polyfills/events.js#L14 )  work like the CJS export(so there are no `default` when you make `require`, just direct object).

I mean that when you make `require('event')` - the `EventEmitter` should be returned, instead of 
```{
  'default': EventEmitter,
  EventEmitter: EventEmitter
}```

**Comment by simonhaenisch** [comment] 2021-12-16 09:12
Just dropping this here because I also had issues with the events polyfill... only in a native environment though, still not sure what the cause was. The error I got was

> TypeError: Object is not a constructor (evaluating 'new EventEmitter()')

I ended up switching to https://github.com/browserify/events which works as expected (used by Webpack as well), and setting `preferBuiltins: false` for the node-resolve plugin.

```
npm install events
```

```js
export default {
  // ...
  plugins: [
    commonjs(),
    nodeResolve({ preferBuiltins: false }),
    // you can probably still use `polyfillNode()` after this for other polyfills,
    // because `events` will have been resolved from the installed package already
    // (in our case we only needed the events polyfill)
  ]
}
```

**Comment by FredKSchott** [comment] 2022-03-30 15:56
Fixed by https://github.com/FredKSchott/rollup-plugin-polyfill-node/pull/42

**Closed by FredKSchott** 2022-03-30 15:56 UTC
